{% set name = "shap" %}
{% set version = "0.42.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slundberg/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 73a9e99dee19e1db4ba058c5bf6209ce2bd49f6e91c3c16e94480f8bbb92c97a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - packaging
    - numpy
  run:
    - python
    - packaging
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - tqdm >4.25.0
    - slicer 0.0.7
    - numba
    - cloudpickle

test:
  requires:
    - pip
    - pytest
    - pytest-mpl
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
  imports:
    - shap

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output of any machine learning model. SHAP connects game theory with local explanations, uniting several previous methods and representing the only possible consistent and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - mrandrewandrade
    - slundberg
    - xhochy
