{% set name = "shap" %}
{% set version = "0.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slundberg/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c280d73715b8e35b6fbd653a14aa29c79bacd35c49252b818baff0a7fcb4a66a

build:
  number: 0
  skip: true  # [py27]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - pandas
    - numpy
    - scikit-learn
    - scikit-image
    - scipy
    - matplotlib-base
    - tqdm
    - ipython
    - slicer
    - numba
test:
  imports:
    - shap

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model.
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output of any machine learning model. SHAP connects game theory with local explanations, uniting several previous methods and representing the only possible consistent and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  dev_url: https://github.com/slundberg/shap

extra:
  recipe-maintainers:
    - mrandrewandrade
    - slundberg
