appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: moB0ORfoj7+DtYmx8dDHesGLxFNfNJQnP9aKLlzAJ7IPGuWaF587Pad6ad5u6uCrEMdE+TBdheA1sqdIywIBszHFTF7aeiRTAxDNFDaK2UeBF9Eg4666YpC9Su2YVCIgB6b/CGkkuwHyR9vNUSwkealYKI/Ur9Tdu8jS0MHYjODAZEb+XUzJ8OvsBoPTbbU6mU3ME8Ic0YkQZnbFh97mLjV99WMsW0xM/6IYzhwHpV+7LKbj1SeuNlqG+apSxCwKol/qSql+L/ayspgVdxXQyWLoBlKmpvCALYDjn1eV8DinH+KevSLLbjBB5cwCCW1K8KT5XqEMe0ShPCKWiGPSfs6yDWf1zlD72zZC2G5+3Dk4EndCpDvko0OaFLAA/blU25ZGPBS/VmZmq7YqO97eoEjMohSzl4zUP0CTLrE9JDsB5BPzKlfQbf5pMDAetPP/0l7GREq6AL+9Yn2/IQtaBYoexdW0nPJlRCO/4K20fZVRZl1CA1bK8uG7vlFKwok9vk73lGnFBo1ptNCRiPctMBKvQVcc17nQfB9JfUgdKCQnyBXS1Mcgt21KEsseGSN8BKqhgE6pL6mdIenm2XQST1d+gmA6O1aKgx7f9GdHeGB+25GfIgpfgPsNiZDV2JYE1giynpaSoWoabxE8quWi7KfCZJ26UVgEziceSDX3X08=}
